version: '2'
services:
#     nginx:
#        build:
#            dockerfile: Dockerfile
#            context: ./nginx
#        ports:
#           - 9000:80
     redis-server:
         image: 'redis'
     api:
         build:
            dockerfile: Dockerfile
            context: ./sample_server
         ports:
            - 9000:9000
     client:
         build:
            dockerfile: Dockerfile
            context: ./chatbot
         volumes:
            - /app/node_modules
            - ./chatbot:/app
         ports:
            - 3000:3000

